import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:water_tracker/Constant/constant.dart';

class Language {
  final int id;
  final String flag;
  final String name;
  final String languageCode;

  Language(this.id, this.flag, this.name, this.languageCode);

  static List<Language> languageList = <Language>[
    Language(0, "🇺🇸", "English", "en"),
    Language(1, "🇩🇰", "Danish", "da"),
    Language(2, "🇫🇷", "French", "fr"),
    Language(3, "🇪🇸", "Spanish", "es"),
    Language(4, "🇩🇪", "German", "de"),
    Language(5, "🇮🇩", "Indonesian", "id"),
    Language(6, "🇯🇵", "Japanese", "ja"),
    Language(7, "🇷🇺", "Russian", "ru"),
    Language(8, "🇸🇦", "Arabic", "ar"),
    Language(9, "🇵🇹", "Portuguese", "pt"),
  ];
}

Future setLocale(String languageCode) async {
  await box.write('languageCode', languageCode);
  Get.updateLocale(Locale(languageCode));
}

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "getstartedscreen": "Water tracker that will remind you when and how much water to drink throughout the day.",
          "login": "Login",
          "enteremail": "Enter Email",
          "emailempty": "Email is empty",
          "entervalidemail": "Enter valid email!",
          "enterpassword": "Enter Password",
          "passwordempty": "Password is empty",
          "entervalidpassword": "Enter valid password!",
          "createaccount": "Create an account ?",
          "register": "Register",
          "youareready": "You Are Ready To Use\nWater Reminder!",
          "customizeyourdrink": "Customize your drink list to\nmatch your preferences and hydration needs.",
          "getstarted": "Get Started",
          "firstname": "First Name",
          "firstnameempty": "First name is empty",
          "lastname": "Last Name",
          "lastnameempty": "Last name is empty",
          "email": "Email",
          "password": "Password",
          "dateofbirth": "Date of Birth",
          "phonenumber": "Phone Number",
          "numberempty": "Number is empty",
          "alreadyaccount": "Already have an account ?",
          "complete": "Complete",
          "next": "Next",
          "gendertitle": "Choose Your Gender",
          "genderdescription": "Based On The Body Type We\nWill Better Calculate Your Hydration Needs.",
          "weighttitle": "How Much Do You Weight?",
          "weightdescription": "Weight Has a Big Impact On Calculating Your\nDaily Water Goal.",
          "weathertitle": "Choose Your Climate/Weather",
          "weatherdescription": "You can set your start and end time to drink\nwater for each day.",
          "goaltitle": "Your Daily Goal",
          "goaldescription": "You Can Tap The Value And Setup Your Own\nManual Daily Goal.",
          "dailygoal": "Daily Goal",
          "recommend": "Recommend",
          "custom": "Custom",
          "cancel": "Cancel",
          "save": "Save",
          "adjust": "Adjust",
          "home": "Home",
          "report": "Report",
          "history": "History",
          "setting": "Setting",
          "hello": "Hello",
          "goodmorning": "Good Morning",
          "goodafternoon": "Good Afternoon",
          "goodevening": "Good Evening",
          "goodnight": "Good Night",
          "youcantadd": "You can't add",
          "water": "Water",
          "remaining": "Remaining",
          "todayrecords": "Today’s Records",
          "notask": "No Task",
          "youhavenotask": "You Have No Task In Your List. Add\nNew Task In Your List",
          "firstglasswater": "Record Today’s First Glass Of Water",
          "lastweek": "Last Week",
          "today": "Today",
          "to": "To",
          "day": "Day",
          "week": "Week",
          "month": "Month",
          "year": "Year",
          "noreporttoday": "No Report Today!",
          "profile": "Profile",
          "reminder": "Reminder",
          "gender": "Gender",
          "language": "Language",
          "theme": "Theme",
          "weight": "Weight",
          "helpfeedback": "Help & Feedback",
          "privacypolicy": "Privacy Policy",
          "ratethisapp": "Rate This App",
          "shareapp": "Share App",
          "logout": "Logout",
          "areyousurelogout": "Are you sure want to logout?",
          "update": "Update",
          "profileupdate": "Profile Update Successfully",
          "sendnotification": "Send Notification",
          "startat": "Start at",
          "endat": "End at",
          "interval": "Interval",
          "message": "Message",
          "every": "Every",
          "minute": "Minute",
          "hour": "Hour",
          "genderupdate": "Gender Update Successfully",
          "todaygoal": "Today Goal",
          "setgoal": "Set Goal",
          "dailygoalupdate": "Daily Goal Update Successfully",
          "systemtheme": "System Theme",
          "themedescription": "When enabled, automatically follows the Dark and Light skin selection located in your device's settings.",
          "light": "Light",
          "dark": "Dark",
          "yourweight": "Your Weight",
          "weightupdate": "Weight Update Successfully",
          "delete": "Delete",
          "yesterday": "Yesterday",
          "noreport": "No Report Found!",
          "nohistory": "No History Found!",
          "average": "Average",
          "goalarchived": "Goal Archived",
          "thegoalwas": "The Goal Was Archived In XX Days. Please Drink More Water!",
          "records": "Records",
          "submit": "Submit",
          "enterfeedback": "Enter Your Feedback",
          "yourfeedback": "Your feedback send successfully",
          "youhavecompleted": "You have completed your today goal",
          "forgetpassword": "Forget Password",
          "getnewpassword": "Get a new password via mail!",
          "send": "Send",
          "termsconditions": "Terms & Conditions"
        },
        'da_DA': {
          "getstartedscreen": "Vandtracker, der vil minde dig om, hvornår og hvor meget vand du skal drikke i løbet af dagen.",
          "login": "Log på",
          "enteremail": "Indtast e-mail",
          "emailempty": "E-mailen er tom",
          "entervalidemail": "Indtast gyldig e-mail!",
          "enterpassword": "Indtast adgangskode",
          "passwordempty": "Adgangskoden er tom",
          "entervalidpassword": "Indtast gyldig adgangskode!",
          "createaccount": "Opret en konto ?",
          "register": "Tilmeld",
          "youareready": "Du er klar\ntil brug",
          "customizeyourdrink": "Tilpas din\ndrinkliste til",
          "getstarted": "Kom igang",
          "firstname": "Fornavn",
          "firstnameempty": "Fornavnet er tomt",
          "lastname": "Efternavn",
          "lastnameempty": "Efternavnet er tomt",
          "email": "E-mail",
          "password": "Adgangskode",
          "dateofbirth": "Fødselsdato",
          "phonenumber": "Telefonnummer",
          "numberempty": "Nummeret er tomt",
          "alreadyaccount": "Har du allerede en bruger ?",
          "complete": "Komplet",
          "next": "Næste",
          "gendertitle": "Vælg dit køn",
          "genderdescription": "Baseret på den kropstype vi",
          "weighttitle": "Hvor meget vejer du?",
          "weightdescription": "Vægt har en stor indflydelse\npå beregningen af din",
          "weathertitle": "Vælg dit klima/vejr",
          "weatherdescription": "Du kan indstille dit start- og\nsluttidspunkt for at drikke",
          "goaltitle": "Dit daglige mål",
          "goaldescription": "Du kan trykke på værdien og\nkonfigurere din egen",
          "dailygoal": "Dagligt mål",
          "recommend": "Anbefale",
          "custom": "Brugerdefinerede",
          "cancel": "Afbestille",
          "save": "Gemme",
          "adjust": "Justere",
          "home": "Hjem",
          "report": "Rapport",
          "history": "Historie",
          "setting": "Indstilling",
          "hello": "Hej",
          "goodmorning": "god morgen",
          "goodafternoon": "God eftermiddag",
          "goodevening": "God aften",
          "goodnight": "Godnat",
          "youcantadd": "Du kan ikke tilføje",
          "water": "Vand",
          "remaining": "Tilbage",
          "todayrecords": "Dagens rekorder",
          "notask": "Ingen opgave",
          "youhavenotask": "Du har ingen opgave på din liste.",
          "firstglasswater": "Optag dagens første glas vand",
          "lastweek": "Sidste uge",
          "today": "I dag",
          "to": "Til",
          "day": "Dag",
          "week": "Uge",
          "month": "Måned",
          "year": "År",
          "noreporttoday": "Ingen rapport i dag!",
          "profile": "Profil",
          "reminder": "Påmindelse",
          "gender": "Køn",
          "language": "Sprog",
          "theme": "Tema",
          "weight": "Vægt",
          "helpfeedback": "Hjælp og feedback",
          "privacypolicy": "Fortrolighedspolitik",
          "ratethisapp": "Bedøm denne app",
          "shareapp": "Del app",
          "logout": "Log ud",
          "areyousurelogout": "Er du sikker på, at du vil logge ud?",
          "update": "Opdatering",
          "profileupdate": "Profilopdatering lykkedes",
          "sendnotification": "Send meddelelse",
          "startat": "Start ved",
          "endat": "Slut kl",
          "interval": "Interval",
          "message": "Besked",
          "every": "Hver",
          "minute": "Minut",
          "hour": "Time",
          "genderupdate": "Opdatering af køn lykkedes",
          "todaygoal": "Dagens mål",
          "setgoal": "Sæt mål",
          "dailygoalupdate": "Daglig målopdatering lykkedes",
          "systemtheme": "System tema",
          "themedescription": "Når den er aktiveret, følger den automatisk valget af mørk og lys hud i din enheds indstillinger.",
          "light": "Lys",
          "dark": "Mørk",
          "yourweight": "Din vægt",
          "weightupdate": "Vægtopdatering med succes",
          "delete": "Slet",
          "yesterday": "I går",
          "noreport": "Ingen rapport fundet!",
          "nohistory": "Ingen historie fundet!",
          "average": "Gennemsnit",
          "goalarchived": "Mål arkiveret",
          "thegoalwas": "Målet blev arkiveret på XX dage.",
          "records": "Optegnelser",
          "submit": "Indsend",
          "enterfeedback": "Indtast din feedback",
          "yourfeedback": "Din feedback er sendt",
          "youhavecompleted": "Du har nået dit mål i dag",
          "forgetpassword": "Glem adgangskode",
          "getnewpassword": "Få en ny adgangskode via mail!",
          "send": "Sende",
          "termsconditions": "Vilkår og Betingelser"
        },
        'fr_FR': {
          "getstartedscreen": "Tracker d'eau qui vous rappellera quand et combien d'eau boire tout au long de la journée.",
          "login": "Se connecter",
          "enteremail": "Entrez l'e-mail",
          "emailempty": "L'e-mail est vide",
          "entervalidemail": "Entrez une adresse email valide!",
          "enterpassword": "Entrer le mot de passe",
          "passwordempty": "Le mot de passe est vide",
          "entervalidpassword": "Entrez un mot de passe valide!",
          "createaccount": "Créer un compte ?",
          "register": "Registre",
          "youareready": "Vous êtes\nprêt à utiliser",
          "customizeyourdrink": "Personnalisez votre\nliste de boissons pour",
          "getstarted": "Commencer",
          "firstname": "Prénom",
          "firstnameempty": "Le prénom est vide",
          "lastname": "Nom de famille",
          "lastnameempty": "Le nom de famille est vide",
          "email": "E-mail",
          "password": "Mot de passe",
          "dateofbirth": "Date de naissance",
          "phonenumber": "Numéro de téléphone",
          "numberempty": "Le numéro est vide",
          "alreadyaccount": "Vous avez déjà un compte ?",
          "complete": "Complet",
          "next": "Suivant",
          "gendertitle": "Choisissez votre genre",
          "genderdescription": "En fonction du\ntype de corps, nous",
          "weighttitle": "Combien pèses-tu?",
          "weightdescription": "Le poids a un impact\nimportant sur le calcul de votre",
          "weathertitle": "Choisissez votre climat/météo",
          "weatherdescription": "Vous pouvez définir votre heure\nde début et de fin pour boire",
          "goaltitle": "Votre objectif quotidien",
          "goaldescription": "Vous pouvez exploiter la\nvaleur et configurer la vôtre",
          "dailygoal": "Objectif quotidien",
          "recommend": "Recommander",
          "custom": "Coutume",
          "cancel": "Annuler",
          "save": "Sauvegarder",
          "adjust": "Ajuster",
          "home": "Maison",
          "report": "Rapport",
          "history": "Histoire",
          "setting": "Paramètre",
          "hello": "Bonjour",
          "goodmorning": "Bonjour",
          "goodafternoon": "Bon après-midi",
          "goodevening": "Bonne soirée",
          "goodnight": "Bonne nuit",
          "youcantadd": "Vous ne pouvez pas ajouter",
          "water": "Eau",
          "remaining": "Restant",
          "todayrecords": "Les records du jour",
          "notask": "Ne pas demander",
          "youhavenotask": "Vous n'avez aucune\ntâche dans votre liste. ",
          "firstglasswater": "Enregistrez le premier verre d’eau d’aujourd’hui",
          "lastweek": "La semaine dernière",
          "today": "Aujourd'hui",
          "to": "À",
          "day": "Jour",
          "week": "Semaine",
          "month": "Mois",
          "year": "Année",
          "noreporttoday": "Aucun rapport aujourd'hui!",
          "profile": "Profil",
          "reminder": "Rappel",
          "gender": "Genre",
          "language": "Langue",
          "theme": "Thème",
          "weight": "Poids",
          "helpfeedback": "Aide et commentaires",
          "privacypolicy": "politique de confidentialité",
          "ratethisapp": "Évaluer l'application",
          "shareapp": "Partager l'application",
          "logout": "Se déconnecter",
          "areyousurelogout": "Etes-vous sûr de vouloir vous déconnecter?",
          "update": "Mise à jour",
          "profileupdate": "Mise à jour du profil réussie",
          "sendnotification": "Envoyer une notification",
          "startat": "Commencer à",
          "endat": "Fin à",
          "interval": "Intervalle",
          "message": "Message",
          "every": "Chaque",
          "minute": "Minute",
          "hour": "Heure",
          "genderupdate": "Mise à jour réussie sur le genre",
          "todaygoal": "Objectif du jour",
          "setgoal": "Fixer un objectif",
          "dailygoalupdate": "Mise à jour quotidienne des objectifs avec succès",
          "systemtheme": "Thème système",
          "themedescription":
              "Lorsqu'il est activé, suit automatiquement la sélection de skin foncé et clair située dans les paramètres de votre appareil.",
          "light": "Lumière",
          "dark": "Sombre",
          "yourweight": "Votre poids",
          "weightupdate": "Mise à jour du poids réussie",
          "delete": "Fente",
          "yesterday": "je vais",
          "noreport": "Ingen rapport fondset!",
          "nohistory": "Fond d'histoire d'Ingen!",
          "average": "Gennemsnit",
          "goalarchived": "Petit arkiveret",
          "thegoalwas": "Målet blev arkiveret på XX jours.",
          "records": "Optegnelser",
          "submit": "Soumettre",
          "enterfeedback": "Entrez vos commentaires",
          "yourfeedback": "Vos commentaires ont été envoyés avec succès",
          "youhavecompleted": "Vous avez atteint votre objectif du jour",
          "forgetpassword": "Mot de passe oublié",
          "getnewpassword": "Recevez un nouveau mot de passe par mail !",
          "send": "Envoyer",
          "termsconditions": "termes et conditions"
        },
        'es_ES': {
          "getstartedscreen": "Rastreador de agua que te recordará cuándo y cuánta agua beber a lo largo del día.",
          "login": "Acceso",
          "enteremail": "Ingrese correo electrónico",
          "emailempty": "El correo electrónico está vacío.",
          "entervalidemail": "¡Ingrese un email valido!",
          "enterpassword": "Introducir la contraseña",
          "passwordempty": "La contraseña está vacía",
          "entervalidpassword": "¡Ingrese una contraseña válida!",
          "createaccount": "Crea una cuenta ?",
          "register": "Registro",
          "youareready": "Estás listo\npara usar",
          "customizeyourdrink": "Personaliza tu\nlista de bebidas para",
          "getstarted": "Empezar",
          "firstname": "Nombre de pila",
          "firstnameempty": "El nombre está vacío.",
          "lastname": "Apellido",
          "lastnameempty": "El apellido está vacío.",
          "email": "Correo electrónico",
          "password": "Contraseña",
          "dateofbirth": "Fecha de nacimiento",
          "phonenumber": "Número de teléfono",
          "numberempty": "El número está vacío",
          "alreadyaccount": "Ya tienes una cuenta ?",
          "complete": "Completo",
          "next": "Próximo",
          "gendertitle": "Elige tu género",
          "genderdescription": "Según el tipo\nde cuerpo que tenemos",
          "weighttitle": "¿Cuanto pesas?",
          "weightdescription": "El peso tiene un gran\nimpacto en el cálculo de su",
          "weathertitle": "Elija su clima/tiempo",
          "weatherdescription": "Puedes establecer tu hora de\ninicio y finalización para beber.",
          "goaltitle": "Tu objetivo diario",
          "goaldescription": "Puede aprovechar el valor\ny configurar el suyo propio",
          "dailygoal": "Objetivo diario",
          "recommend": "Recomendar",
          "custom": "Costumbre",
          "cancel": "Cancelar",
          "save": "Ahorrar",
          "adjust": "Ajustar",
          "home": "Hogar",
          "report": "Informe",
          "history": "Historia",
          "setting": "Configuración",
          "hello": "Hola",
          "goodmorning": "Buen día",
          "goodafternoon": "Buenas tardes",
          "goodevening": "Buenas noches",
          "goodnight": "Buenas noches",
          "youcantadd": "no puedes agregar",
          "water": "Agua",
          "remaining": "Restante",
          "todayrecords": "Los récords de hoy",
          "notask": "No preguntar",
          "youhavenotask": "No tienes ninguna\ntarea en tu lista.",
          "firstglasswater": "Graba el primer vaso de agua de hoy",
          "lastweek": "La semana pasada",
          "today": "Hoy",
          "to": "A",
          "day": "Día",
          "week": "Semana",
          "month": "Mes",
          "year": "Año",
          "noreporttoday": "¡No hay informe hoy!",
          "profile": "Perfil",
          "reminder": "Recordatorio",
          "gender": "Género",
          "language": "Idioma",
          "theme": "Tema",
          "weight": "Peso",
          "helpfeedback": "Ayuda y comentarios",
          "privacypolicy": "política de privacidad",
          "ratethisapp": "Califica esta aplicación",
          "shareapp": "Compartir aplicación",
          "logout": "Cerrar sesión",
          "areyousurelogout": "¿Estás seguro de que quieres cerrar sesión?",
          "update": "Actualizar",
          "profileupdate": "Actualización de perfil exitosa",
          "sendnotification": "Enviar notificación",
          "startat": "Empieza en",
          "endat": "Termina en",
          "interval": "Intervalo",
          "message": "Mensaje",
          "every": "Cada",
          "minute": "Minuto",
          "hour": "Hora",
          "genderupdate": "Actualización de Género con éxito",
          "todaygoal": "Objetivo de hoy",
          "setgoal": "Establecer una meta",
          "dailygoalupdate": "Actualización diaria de objetivos con éxito",
          "systemtheme": "Tema del sistema",
          "themedescription":
              "Cuando está habilitado, sigue automáticamente la selección de máscara Oscura y Clara ubicada en la configuración de su dispositivo.",
          "light": "Luz",
          "dark": "Oscuro",
          "yourweight": "Tu peso",
          "weightupdate": "Actualización de peso exitosamente",
          "delete": "Fente",
          "yesterday": "je vais",
          "noreport": "Ingen rapport fondset!",
          "nohistory": "Fond d'histoire d'Ingen!",
          "average": "Gennemsnit",
          "goalarchived": "Petit arkiveret",
          "thegoalwas": "Målet blev arkiveret på XX jours.",
          "records": "Optegnelser",
          "submit": "Soumettre",
          "enterfeedback": "Entrez vos commentaires",
          "yourfeedback": "Vos commentaires ont été envoyés avec succès",
          "youhavecompleted": "Has completado tu objetivo de hoy",
          "forgetpassword": "Contraseña olvidada",
          "getnewpassword": "¡Obtenga una nueva contraseña por correo!",
          "send": "Enviar",
          "termsconditions": "Términos y condiciones"
        },
        'de_DE': {
          "getstartedscreen": "Wasser-Tracker, der Sie daran erinnert, wann und wie viel Wasser Sie den ganzen Tag über trinken müssen.",
          "login": "Anmeldung",
          "enteremail": "Email eingeben",
          "emailempty": "E-Mail ist leer",
          "entervalidemail": "Geben Sie eine gültige E-Mail-Adresse ein!",
          "enterpassword": "Passwort eingeben",
          "passwordempty": "Das Passwort ist leer",
          "entervalidpassword": "Geben Sie ein gültiges Passwort ein!",
          "createaccount": "Ein Konto erstellen ?",
          "register": "Registrieren",
          "youareready": "Sie sind einsatzbereit\n",
          "customizeyourdrink": "Passen Sie Ihre Getränkekarte an\n",
          "getstarted": "Loslegen",
          "firstname": "Vorname",
          "firstnameempty": "Der Vorname ist leer",
          "lastname": "Familienname, Nachname",
          "lastnameempty": "Nachname ist leer",
          "email": "Email",
          "password": "Passwort",
          "dateofbirth": "Geburtsdatum",
          "phonenumber": "Telefonnummer",
          "numberempty": "Nummer ist leer",
          "alreadyaccount": "Sie haben bereits ein Konto ?",
          "complete": "Vollständig",
          "next": "Nächste",
          "gendertitle": "Wählen Sie ihr Geschlecht",
          "genderdescription": "Basierend auf dem\nKörpertyp, den wir haben",
          "weighttitle": "Wie viel wiegst du?",
          "weightdescription": "Das Gewicht hat einen großen\nEinfluss auf die Berechnung Ihres",
          "weathertitle": "Wählen Sie Ihr Klima/Wetter",
          "weatherdescription": "Sie können Ihre Start- und\nEndzeit für das Trinken festlegen",
          "goaltitle": "Ihr tägliches Ziel",
          "goaldescription": "Sie können auf den Wert tippen\nund Ihren eigenen Wert einrichten",
          "dailygoal": "Tagesziel",
          "recommend": "Empfehlen",
          "custom": "Brauch",
          "cancel": "Stornieren",
          "save": "Speichern",
          "adjust": "Anpassen",
          "home": "Heim",
          "report": "Bericht",
          "history": "Geschichte",
          "setting": "Einstellung",
          "hello": "Hallo",
          "goodmorning": "Guten Morgen",
          "goodafternoon": "Guten Tag",
          "goodevening": "Guten Abend",
          "goodnight": "Gute Nacht",
          "youcantadd": "Sie können nicht hinzufügen",
          "water": "Wasser",
          "remaining": "Übrig",
          "todayrecords": "Heutige Aufzeichnungen",
          "notask": "Nicht fragen",
          "youhavenotask": "Sie haben keine\nAufgabe in Ihrer Liste.",
          "firstglasswater": "Zeichnen Sie das erste Glas Wasser des heutigen Tages auf",
          "lastweek": "Letzte Woche",
          "today": "Heute",
          "to": "Zu",
          "day": "Tag",
          "week": "Woche",
          "month": "Monat",
          "year": "Jahr",
          "noreporttoday": "Kein Bericht heute!",
          "profile": "Profil",
          "reminder": "Erinnerung",
          "gender": "Geschlecht",
          "language": "Sprache",
          "theme": "Thema",
          "weight": "Gewicht",
          "helpfeedback": "Hilfe und Feedback",
          "privacypolicy": "Datenschutzrichtlinie",
          "ratethisapp": "Bewerte diese App",
          "shareapp": "App teilen",
          "logout": "Ausloggen",
          "areyousurelogout": "Möchten Sie sich wirklich abmelden?",
          "update": "Aktualisieren",
          "profileupdate": "Profilaktualisierung erfolgreich",
          "sendnotification": "Benachrichtigung senden",
          "startat": "Anfangen bei",
          "endat": "Ende um",
          "interval": "Intervall",
          "message": "Nachricht",
          "every": "Jeden",
          "minute": "Minute",
          "hour": "Stunde",
          "genderupdate": "Geschlechtsaktualisierung erfolgreich",
          "todaygoal": "Heute Ziel",
          "setgoal": "Ziel setzen",
          "dailygoalupdate": "Tägliche Zielaktualisierung erfolgreich",
          "systemtheme": "Systemthema",
          "themedescription":
              "Wenn diese Option aktiviert ist, folgt sie automatisch der Auswahl „Dunkel“ und „Hell“, die Sie in den Einstellungen Ihres Geräts finden.",
          "light": "Licht",
          "dark": "Dunkel",
          "yourweight": "Dein Gewicht",
          "weightupdate": "Gewichtsaktualisierung erfolgreich",
          "delete": "Löschen",
          "yesterday": "Gestern",
          "noreport": "Kein Bericht gefunden!",
          "nohistory": "Kein Verlauf gefunden!",
          "average": "Durchschnitt",
          "goalarchived": "Ziel archiviert",
          "thegoalwas": "Das Ziel wurde in XX Tagen archiviert.",
          "records": "Aufzeichnungen",
          "submit": "Einreichen",
          "enterfeedback": "Geben Sie Ihr Feedback ein",
          "yourfeedback": "Ihr Feedback wurde erfolgreich gesendet",
          "youhavecompleted": "Sie haben Ihr heutiges Ziel erreicht",
          "forgetpassword": "Passwort vergessen",
          "getnewpassword": "Erhalten Sie ein neues Passwort per E-Mail!",
          "send": "Schicken",
          "termsconditions": "Terms & amp; Bedingungen"
        },
        'id_ID': {
          "getstartedscreen": "Pelacak air yang akan mengingatkan Anda kapan dan berapa banyak air yang harus diminum sepanjang hari.",
          "login": "Gabung",
          "enteremail": "Masukan email",
          "emailempty": "Emailnya kosong",
          "entervalidemail": "Masuk kan email yang benar!",
          "enterpassword": "Masukkan kata kunci",
          "passwordempty": "Kata sandi kosong",
          "entervalidpassword": "Masukkan kata sandi yang valid!",
          "createaccount": "Buat sebuah akun ?",
          "register": "Daftar",
          "youareready": "Anda Siap\nDigunakan",
          "customizeyourdrink": "Sesuaikan daftar\nminuman Anda",
          "getstarted": "Memulai",
          "firstname": "Nama depan",
          "firstnameempty": "Nama depan kosong",
          "lastname": "Nama keluarga",
          "lastnameempty": "Nama belakang kosong",
          "email": "Surel",
          "password": "Kata sandi",
          "dateofbirth": "Tanggal lahir",
          "phonenumber": "Nomor telepon",
          "numberempty": "Nomornya kosong",
          "alreadyaccount": "Sudah memiliki akun ?",
          "complete": "Menyelesaikan",
          "next": "Berikutnya",
          "gendertitle": "Pilih Jenis Kelamin Anda",
          "genderdescription": "Berdasarkan Tipe\nTubuh Kita",
          "weighttitle": "Berapa beratmu?",
          "weightdescription": "Berat Badan Memiliki Dampak\nBesar Pada Perhitungan Anda",
          "weathertitle": "Pilih Iklim/Cuaca Anda",
          "weatherdescription": "Anda dapat mengatur waktu\nmulai dan berakhir untuk minum",
          "goaltitle": "Tujuan Harian Anda",
          "goaldescription": "Anda Dapat Mengetuk\nNilainya Dan Mengaturnya Sendiri",
          "dailygoal": "Tujuan Harian",
          "recommend": "Menyarankan",
          "custom": "Kebiasaan",
          "cancel": "Membatalkan",
          "save": "Menyimpan",
          "adjust": "Menyesuaikan",
          "home": "Rumah",
          "report": "Laporan",
          "history": "Sejarah",
          "setting": "Pengaturan",
          "hello": "Halo",
          "goodmorning": "Selamat pagi",
          "goodafternoon": "Selamat siang",
          "goodevening": "Selamat malam",
          "goodnight": "Selamat malam",
          "youcantadd": "Anda tidak dapat menambahkan",
          "water": "Air",
          "remaining": "Tersisa",
          "todayrecords": "Rekor Hari Ini",
          "notask": "Tidak bertanya",
          "youhavenotask": "Anda Tidak Memiliki\nTugas Dalam Daftar Anda.",
          "firstglasswater": "Rekam Segelas Air Pertama Hari Ini",
          "lastweek": "Minggu lalu",
          "today": "Hari ini",
          "to": "Ke",
          "day": "Hari",
          "week": "Pekan",
          "month": "Bulan",
          "year": "Tahun",
          "noreporttoday": "Tidak Ada Laporan Hari Ini!",
          "profile": "Profil",
          "reminder": "Pengingat",
          "gender": "Jenis kelamin",
          "language": "Bahasa",
          "theme": "Tema",
          "weight": "Berat",
          "helpfeedback": "Bantuan & Masukan",
          "privacypolicy": "Kebijakan pribadi",
          "ratethisapp": "Nilai aplikasi ini",
          "shareapp": "Bagikan Aplikasi",
          "logout": "Keluar",
          "areyousurelogout": "Apakah Anda yakin ingin logout?",
          "update": "Memperbarui",
          "profileupdate": "Pembaruan Profil Berhasil",
          "sendnotification": "Kirim Pemberitahuan",
          "startat": "Dimulai dari",
          "endat": "Berakhir pada",
          "interval": "Selang",
          "message": "Pesan",
          "every": "Setiap",
          "minute": "Menit",
          "hour": "Jam",
          "genderupdate": "Pembaruan Gender Berhasil",
          "todaygoal": "Tujuan Hari ini",
          "setgoal": "Tetapkan Tujuan",
          "dailygoalupdate": "Pembaruan Sasaran Harian Berhasil",
          "systemtheme": "Tema Sistem",
          "themedescription": "Saat diaktifkan, secara otomatis mengikuti pilihan kulit Gelap dan Terang yang terletak di pengaturan perangkat Anda.",
          "light": "Lampu",
          "dark": "Gelap",
          "yourweight": "Berat badanmu",
          "weightupdate": "Pembaruan Berat Badan Berhasil",
          "delete": "Menghapus",
          "yesterday": "Kemarin",
          "noreport": "Tidak Ada Laporan yang Ditemukan!",
          "nohistory": "Tidak Ada Riwayat yang Ditemukan!",
          "average": "Rata-rata",
          "goalarchived": "Sasaran Diarsipkan",
          "thegoalwas": "Tujuannya Diarsipkan Dalam XX Hari.",
          "records": "Catatan",
          "submit": "Kirim",
          "enterfeedback": "Masukkan Masukan Anda",
          "yourfeedback": "Masukan Anda berhasil dikirim",
          "youhavecompleted": "Anda telah menyelesaikan tujuan Anda hari ini",
          "forgetpassword": "Lupa Password",
          "getnewpassword": "Dapatkan kata sandi baru melalui surat!",
          "send": "Mengirim",
          "termsconditions": "Syarat & Ketentuan"
        },
        'ja_JA': {
          "getstartedscreen": "1 日を通していつ、どのくらい水を飲むべきかを知らせる水分トラッカー。",
          "login": "ログイン",
          "enteremail": "メールアドレスを入力して",
          "emailempty": "メールが空です",
          "entervalidemail": "有効な電子メールを入力してください！",
          "enterpassword": "パスワードを入力する",
          "passwordempty": "パスワードが空です",
          "entervalidpassword": "有効なパスワードを入力してください!",
          "createaccount": "アカウントを作成する ？",
          "register": "登録する",
          "youareready": "使用する準\n備ができました",
          "customizeyourdrink": "ドリンクリスト\nをカスタマイズして、",
          "getstarted": "始めましょう",
          "firstname": "ファーストネーム",
          "firstnameempty": "名が空です",
          "lastname": "苗字",
          "lastnameempty": "姓が空です",
          "email": "Eメール",
          "password": "パスワード",
          "dateofbirth": "生年月日",
          "phonenumber": "電話番号",
          "numberempty": "番号が空です",
          "alreadyaccount": "すでにアカウントをお持ちですか ？",
          "complete": "完了",
          "next": "次",
          "gendertitle": "性別を選択してください",
          "genderdescription": "体型に基\nづいて私たちは",
          "weighttitle": "体重はどれくらいですか?",
          "weightdescription": "体重は体重の計算に\n大きな影響を与えます",
          "weathertitle": "気候/天候を選択してください",
          "weatherdescription": "飲み始めと終わ\nりの時間を設定できる",
          "goaltitle": "毎日の目標",
          "goaldescription": "値をタップして独自の\n設定を行うことができます",
          "dailygoal": "毎日の目標",
          "recommend": "推薦する",
          "custom": "カスタム",
          "cancel": "キャンセル",
          "save": "保存",
          "adjust": "調整する",
          "home": "家",
          "report": "報告",
          "history": "歴史",
          "setting": "設定",
          "hello": "こんにちは",
          "goodmorning": "おはよう",
          "goodafternoon": "こんにちは",
          "goodevening": "こんばんは",
          "goodnight": "おやすみ",
          "youcantadd": "追加はできません",
          "water": "水",
          "remaining": "残り",
          "todayrecords": "今日の記録",
          "notask": "聞かない",
          "youhavenotask": "リストにタスクがありません。",
          "firstglasswater": "今日の最初の一杯目の水を記録する",
          "lastweek": "先週",
          "today": "今日",
          "to": "に",
          "day": "日",
          "week": "週",
          "month": "月",
          "year": "年",
          "noreporttoday": "今日はレポートはありません!",
          "profile": "プロフィール",
          "reminder": "リマインダー",
          "gender": "性別",
          "language": "言語",
          "theme": "テーマ",
          "weight": "重さ",
          "helpfeedback": "ヘルプとフィードバック",
          "privacypolicy": "プライバシーポリシー",
          "ratethisapp": "このアプリを評価する",
          "shareapp": "アプリを共有する",
          "logout": "ログアウト",
          "areyousurelogout": "本当にログアウトしてもよろしいですか?",
          "update": "アップデート",
          "profileupdate": "プロファイルが正常に更新されました",
          "sendnotification": "通知を送信する",
          "startat": "から開始",
          "endat": "終了時刻",
          "interval": "間隔",
          "message": "メッセージ",
          "every": "毎",
          "minute": "分",
          "hour": "時間",
          "genderupdate": "性別の更新が成功しました",
          "todaygoal": "今日の目標",
          "setgoal": "目標を設定する",
          "dailygoalupdate": "毎日の目標が正常に更新されました",
          "systemtheme": "システムテーマ",
          "themedescription": "有効にすると、デバイスの設定にあるダークスキンとライトスキンの選択に自動的に従います。",
          "light": "ライト",
          "dark": "暗い",
          "yourweight": "あなたの体重",
          "weightupdate": "体重が正常に更新されました",
          "delete": "消去",
          "yesterday": "昨日",
          "noreport": "レポートが見つかりません!",
          "nohistory": "履歴が見つかりません!",
          "average": "平均",
          "goalarchived": "目標がアーカイブされました",
          "thegoalwas": "目標は XX 日以内にアーカイブされました。",
          "records": "記録",
          "submit": "提出する",
          "enterfeedback": "フィードバックを入力してください",
          "yourfeedback": "フィードバックは正常に送信されました",
          "youhavecompleted": "今日の目標を達成しました",
          "forgetpassword": "パスワードを忘れた場合",
          "getnewpassword": "新しいパスワードをメールで取得してください!",
          "send": "送信",
          "termsconditions": "利用規約"
        },
        'ru_RU': {
          "getstartedscreen": "Водный трекер, который будет напоминать вам, когда и сколько воды нужно выпить в течение дня.",
          "login": "Авторизоваться",
          "enteremail": "Введите адрес электронной почты",
          "emailempty": "Электронная почта пуста",
          "entervalidemail": "Введите действующий адрес электронной почты!",
          "enterpassword": "Введите пароль",
          "passwordempty": "Пароль пуст",
          "entervalidpassword": "Введите действительный пароль!",
          "createaccount": "Завести аккаунт ?",
          "register": "регистр",
          "youareready": "Вы готовы\nиспользовать",
          "customizeyourdrink": "Настройте свой\nсписок напитков, чтобы",
          "getstarted": "Начать",
          "firstname": "Имя",
          "firstnameempty": "Имя пусто",
          "lastname": "Фамилия",
          "lastnameempty": "Фамилия пуста",
          "email": "Электронная почта",
          "password": "Пароль",
          "dateofbirth": "Дата рождения",
          "phonenumber": "Номер телефона",
          "numberempty": "Номер пуст",
          "alreadyaccount": "Уже есть аккаунт?",
          "complete": "Полный",
          "next": "Следующий",
          "gendertitle": "Выберите свой пол",
          "genderdescription": "В зависимости от\nтипа телосложения мы",
          "weighttitle": "Сколько ты весишь?",
          "weightdescription": "Вес имеет большое влияние\nна расчет вашего веса.",
          "weathertitle": "Выберите свой климат/погоду",
          "weatherdescription": "Вы можете установить\nвремя начала и окончания питья.",
          "goaltitle": "Ваша ежедневная цель",
          "goaldescription": "Вы можете нажать на\nзначение и настроить свое собственное",
          "dailygoal": "Ежедневная цель",
          "recommend": "Рекомендовать",
          "custom": "Обычай",
          "cancel": "Отмена",
          "save": "Сохранять",
          "adjust": "Регулировать",
          "home": "Дом",
          "report": "Отчет",
          "history": "История",
          "setting": "Параметр",
          "hello": "Привет",
          "goodmorning": "Доброе утро",
          "goodafternoon": "Добрый день",
          "goodevening": "Добрый вечер",
          "goodnight": "Спокойной ночи",
          "youcantadd": "Вы не можете добавить",
          "water": "Вода",
          "remaining": "Оставшийся",
          "todayrecords": "Сегодняшние рекорды",
          "notask": "Не спрашивай",
          "youhavenotask": "У вас нет задачи в вашем списке.",
          "firstglasswater": "Запишите первый за сегодня стакан воды",
          "lastweek": "На прошлой неделе",
          "today": "Сегодня",
          "to": "К",
          "day": "День",
          "week": "Неделя",
          "month": "Месяц",
          "year": "Год",
          "noreporttoday": "Нет отчета сегодня!",
          "profile": "Профиль",
          "reminder": "Напоминание",
          "gender": "Пол",
          "language": "Язык",
          "theme": "Тема",
          "weight": "Масса",
          "helpfeedback": "Помощь и обратная связь",
          "privacypolicy": "политика конфиденциальности",
          "ratethisapp": "Оцени это приложение",
          "shareapp": "Поделиться приложением",
          "logout": "Выйти",
          "areyousurelogout": "Вы уверены, что хотите выйти?",
          "update": "Обновлять",
          "profileupdate": "Профиль обновлен успешно",
          "sendnotification": "Отправить уведомление",
          "startat": "Начать с",
          "endat": "Конец в",
          "interval": "Интервал",
          "message": "Сообщение",
          "every": "Каждый",
          "minute": "минута",
          "hour": "Час",
          "genderupdate": "Гендерное обновление успешно выполнено",
          "todaygoal": "Цель на сегодня",
          "setgoal": "Установить цель",
          "dailygoalupdate": "Ежедневная цель обновлена успешно",
          "systemtheme": "Системная тема",
          "themedescription":
              "Если эта функция включена, автоматически следует выбор темного и светлого скина, указанный в настройках вашего устройства.",
          "light": "Свет",
          "dark": "Темный",
          "yourweight": "Твой вес",
          "weightupdate": "Обновление веса успешно выполнено",
          "delete": "Удалить",
          "yesterday": "Вчера",
          "noreport": "Отчет не найден!",
          "nohistory": "История не найдена!",
          "average": "Средний",
          "goalarchived": "Цель в архиве",
          "thegoalwas": "Цель была заархивирована через XX дней.",
          "records": "Рекорды",
          "submit": "Представлять на рассмотрение",
          "enterfeedback": "Введите свой отзыв",
          "yourfeedback": "Ваш отзыв успешно отправлен",
          "youhavecompleted": "Вы выполнили свою сегодняшнюю цель",
          "forgetpassword": "Забыть пароль",
          "getnewpassword": "Получите новый пароль по почте!",
          "send": "Отправлять",
          "termsconditions": "Условия использования"
        },
        'ar_SA': {
          "getstartedscreen": "جهاز تعقب المياه الذي سيذكرك بموعد وكمية الماء التي يجب شربها طوال اليوم.",
          "login": "تسجيل الدخول",
          "enteremail": "أدخل البريد الإلكتروني",
          "emailempty": "البريد الإلكتروني فارغ",
          "entervalidemail": "أدخل بريدًا إلكترونيًا صالحًا!",
          "enterpassword": "أدخل كلمة المرور",
          "passwordempty": "كلمة المرور فارغة",
          "entervalidpassword": "أدخل كلمة مرور صالحة!",
          "createaccount": "إنشاء حساب ؟",
          "register": "يسجل",
          "youareready": "أنت جاهز\n للاستخداn",
          "customizeyourdrink": "تخصيص قائمة\n المشروبات الخاصة بك ل",
          "getstarted": "البدء",
          "firstname": "الاسم الأول",
          "firstnameempty": "الاسم الأول فارغ",
          "lastname": "اسم العائلة",
          "lastnameempty": "الاسم الأخير فارغ",
          "email": "بريد إلكتروني",
          "password": "كلمة المرور",
          "dateofbirth": "تاريخ الميلاد",
          "phonenumber": "رقم التليفون",
          "numberempty": "الرقم فارغ",
          "alreadyaccount": "هل لديك حساب ؟",
          "complete": "مكتمل",
          "next": "التالي",
          "gendertitle": "اختيار جنسك",
          "genderdescription": "بناء على\n نوع الجسم نحن",
          "weighttitle": "كم وزنك؟",
          "weightdescription": "الوزن له تأثير\n كبير على حساب الخاص بك",
          "weathertitle": "اختر المناخ/الطقس الخاص بك",
          "weatherdescription": "يمكنك ضبط وقت\n البدء والانتهاء للشرب",
          "goaltitle": "هدفك اليومي",
          "goaldescription": "يمكنك النقر على\n القيمة وإعداد القيمة الخاصة بك",
          "dailygoal": "الهدف اليومي",
          "recommend": "يوصي",
          "custom": "مخصص",
          "cancel": "يلغي",
          "save": "يحفظ",
          "adjust": "يُعدِّل",
          "home": "بيت",
          "report": "تقرير",
          "history": "تاريخ",
          "setting": "جلسة",
          "hello": "مرحبًا",
          "goodmorning": "صباح الخير",
          "goodafternoon": "مساء الخير",
          "goodevening": "مساء الخير",
          "goodnight": "طاب مساؤك",
          "youcantadd": "لا يمكنك الإضافة",
          "water": "ماء",
          "remaining": "متبقي",
          "todayrecords": "سجلات اليوم",
          "notask": "لا توجد مهمة",
          "youhavenotask": "ليس لديك أي مهمة في قائمتك. ",
          "firstglasswater": "سجل أول كوب ماء اليوم",
          "lastweek": "الأسبوع الماضي",
          "today": "اليوم",
          "to": "ل",
          "day": "يوم",
          "week": "أسبوع",
          "month": "شهر",
          "year": "سنة",
          "noreporttoday": "لا يوجد تقرير اليوم!",
          "profile": "حساب تعريفي",
          "reminder": "تذكير",
          "gender": "جنس",
          "language": "لغة",
          "theme": "سمة",
          "weight": "وزن",
          "helpfeedback": "المساعدة والتعليقات",
          "privacypolicy": "سياسة الخصوصية",
          "ratethisapp": "قيم هذا التطبيق",
          "shareapp": "شارك التطبيق",
          "logout": "تسجيل خروج",
          "areyousurelogout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "update": "تحديث",
          "profileupdate": "تم تحديث الملف الشخصي بنجاح",
          "sendnotification": "إرسال الإخطار",
          "startat": "تبدأ في",
          "endat": "يغلق عند مستوى",
          "interval": "فاصلة",
          "message": "رسالة",
          "every": "كل",
          "minute": "دقيقة",
          "hour": "ساعة",
          "genderupdate": "تم تحديث الجنس بنجاح",
          "todaygoal": "هدف اليوم",
          "setgoal": "تحديد الهدف",
          "dailygoalupdate": "تم تحديث الهدف اليومي بنجاح",
          "systemtheme": "موضوع النظام",
          "themedescription": "عند التمكين، يتبع تلقائيًا تحديد البشرة الداكنة والفاتحة الموجود في إعدادات جهازك.",
          "light": "ضوء",
          "dark": "مظلم",
          "yourweight": "وزنك",
          "weightupdate": "تم تحديث الوزن بنجاح",
          "delete": "يمسح",
          "yesterday": "أمس",
          "noreport": "لم يتم العثور على تقرير!",
          "nohistory": "لم يتم العثور على التاريخ!",
          "average": "متوسط",
          "goalarchived": "الهدف مؤرشف",
          "thegoalwas": "تمت أرشفة الهدف خلال XX يومًا. ",
          "records": "السجلات",
          "submit": "يُقدِّم",
          "enterfeedback": "أدخل ملاحظاتك",
          "yourfeedback": "تم إرسال ملاحظاتك بنجاح",
          "youhavecompleted": "لقد أكملت هدفك اليوم",
          "forgetpassword": "نسيت كلمة المرور",
          "getnewpassword": "الحصول على كلمة مرور جديدة عبر البريد!",
          "send": "يرسل",
          "termsconditions": "البنود و الظروف"
        },
        'pt_PT': {
          "getstartedscreen": "Rastreador de água que irá lembrá-lo quando e quanta água beber ao longo do dia.",
          "login": "Conecte-se",
          "enteremail": "Digite o e-mail",
          "emailempty": "O e-mail está vazio",
          "entervalidemail": "Digite um e-mail válido!",
          "enterpassword": "Digite a senha",
          "passwordempty": "A senha está vazia",
          "entervalidpassword": "Digite uma senha válida!",
          "createaccount": "Crie a sua conta aqui ?",
          "register": "Registro",
          "youareready": "Você está\npronto para usar",
          "customizeyourdrink": "Personalize sua\nlista de bebidas para",
          "getstarted": "Iniciar",
          "firstname": "Primeiro nome",
          "firstnameempty": "O primeiro nome está vazio",
          "lastname": "Sobrenome",
          "lastnameempty": "O sobrenome está vazio",
          "email": "E-mail",
          "password": "Senha",
          "dateofbirth": "Data de nascimento",
          "phonenumber": "Número de telefone",
          "numberempty": "O número está vazio",
          "alreadyaccount": "Já tem uma conta ?",
          "complete": "Completo",
          "next": "Próximo",
          "gendertitle": "Escolha seu gênero",
          "genderdescription": "Com base no\ntipo de corpo, nós",
          "weighttitle": "Quanto você pesa?",
          "weightdescription": "O peso tem um grande\nimpacto no cálculo do seu",
          "weathertitle": "Escolha o seu clima/tempo",
          "weatherdescription": "Você pode definir seu\nhorário de início e término para beber",
          "goaltitle": "Sua meta diária",
          "goaldescription": "Você pode aproveitar o\nvalor e configurar o seu próprio",
          "dailygoal": "Meta diária",
          "recommend": "Recomendar",
          "custom": "Personalizado",
          "cancel": "Cancelar",
          "save": "Salvar",
          "adjust": "Ajustar",
          "home": "Lar",
          "report": "Relatório",
          "history": "História",
          "setting": "Contexto",
          "hello": "Olá",
          "goodmorning": "Bom dia",
          "goodafternoon": "Boa tarde",
          "goodevening": "Boa noite",
          "goodnight": "Boa noite",
          "youcantadd": "Você não pode adicionar",
          "water": "Água",
          "remaining": "Restante",
          "todayrecords": "Registros de hoje",
          "notask": "Não pergunte",
          "youhavenotask": "Você não tem nenhuma\ntarefa em sua lista.",
          "firstglasswater": "Grave o primeiro copo de água de hoje",
          "lastweek": "Semana passada",
          "today": "Hoje",
          "to": "Para",
          "day": "Dia",
          "week": "Semana",
          "month": "Mês",
          "year": "Ano",
          "noreporttoday": "Nenhum relatório hoje!",
          "profile": "Perfil",
          "reminder": "Lembrete",
          "gender": "Gênero",
          "language": "Linguagem",
          "theme": "Tema",
          "weight": "Peso",
          "helpfeedback": "Ajuda e comentários",
          "privacypolicy": "política de Privacidade",
          "ratethisapp": "Avalie este aplicativo",
          "shareapp": "Compartilhe o aplicativo",
          "logout": "Sair",
          "areyousurelogout": "Tem certeza de que deseja sair?",
          "update": "Atualizar",
          "profileupdate": "Atualização de perfil com sucesso",
          "sendnotification": "Enviar notificação",
          "startat": "Começa ás",
          "endat": "Termina em",
          "interval": "Intervalo",
          "message": "Mensagem",
          "every": "Todo",
          "minute": "Minuto",
          "hour": "Hora",
          "genderupdate": "Atualização de gênero com sucesso",
          "todaygoal": "Meta de hoje",
          "setgoal": "Definir meta",
          "dailygoalupdate": "Atualização diária da meta com sucesso",
          "systemtheme": "Tema do sistema",
          "themedescription":
              "Quando ativado, segue automaticamente a seleção de pele Escura e Clara localizada nas configurações do seu dispositivo.",
          "light": "Luz",
          "dark": "Escuro",
          "yourweight": "Seu peso",
          "weightupdate": "Atualização de peso com sucesso",
          "delete": "Excluir",
          "yesterday": "Ontem",
          "noreport": "Nenhum relatório encontrado!",
          "nohistory": "Nenhum histórico encontrado!",
          "average": "Média",
          "goalarchived": "Meta arquivada",
          "thegoalwas": "A meta foi arquivada em XX dias. ",
          "records": "Registros",
          "submit": "Enviar",
          "enterfeedback": "Insira seu feedback",
          "yourfeedback": "Seu feedback foi enviado com sucesso",
          "youhavecompleted": "Você completou sua meta de hoje",
          "forgetpassword": "Esqueceu a senha",
          "getnewpassword": "Obtenha uma nova senha por e-mail!",
          "send": "Enviar",
          "termsconditions": "termos e Condições"
        },
      };
}
